import {renderCreative} from './creative-render.js';
import {FRENCH_CONCEPTS,qualityGate} from './creative-strategy.js';
const $=id=>document.getElementById(id);
const marketConfig={fr:{locale:'fr-FR',label:'France'},us:{locale:'en-US',label:'USA'},es:{locale:'es-ES',label:'Espagne'},de:{locale:'de-DE',label:'Allemagne'}};
const FALLBACK_VARIANTS={us:[['I understand English… but when I have to speak, I freeze.','The worst part? I know the words.','But the second I speak… nothing.','So I changed how I practiced.','And suddenly I actually wanted to keep going.','Link in bio.']],es:[['Entiendo inglés… pero cuando tengo que hablar, me bloqueo.','Lo peor es que conozco las palabras.','Pero al hablar… nada.','Así que probé otra forma.','Y por fin me dieron ganas de seguir practicando.','Link in bio.']],de:[['Ich verstehe Englisch… aber beim Sprechen blockiere ich.','Das Schlimmste? Ich kenne die Wörter.','Aber sobald ich sprechen soll… nichts.','Also habe ich etwas anderes ausprobiert.','Und plötzlich wollte ich weiterüben.','Link in Bio.']]};
let selectedConcept=null,bestVideos=[];const clipCache=new Map();
const DB_NAME='sunami-creative-library';const STORE='videos';
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function saveVideo(item){try{const db=await openDB();await new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(item);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});db.close();return true}catch(e){console.warn('IndexedDB quota',e);return false}}
async function loadVideos(){try{const db=await openDB();const rows=await new Promise((res,rej)=>{const tx=db.transaction(STORE,'readonly');const q=tx.objectStore(STORE).getAll();q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)});db.close();return rows}catch{return []}}
async function refreshLibrary(){const rows=await loadVideos();const grid=$('libraryGrid');if(!grid)return;grid.innerHTML='';rows.sort((a,b)=>a.index-b.index).forEach(v=>{const el=document.createElement('article');el.className='library-card';const blob=new Blob([v.blob],{type:v.type||'video/webm'});const url=URL.createObjectURL(blob);el.innerHTML=`<div class="library-number">#${String(v.index+1).padStart(2,'0')}</div><video controls playsinline preload="metadata" src="${url}"></video><a class="download" download="${v.filename}" href="${url}">⬇ Télécharger</a><small>${v.conceptId} · ${v.format}</small>`;grid.appendChild(el)});$('libraryStatus').textContent=`${rows.length} / 50 vidéos sauvegardées sur cet appareil.`}
function conceptPool(market,brief){if(market==='fr')return FRENCH_CONCEPTS.map(c=>({...c,brief}));const base=FALLBACK_VARIANTS[market]||FALLBACK_VARIANTS.us;return Array.from({length:50},(_,i)=>({id:`${market.toUpperCase()}-${String(i+1).padStart(2,'0')}`,market,locale:marketConfig[market].locale,hook:base[0][0],lines:base[0],searches:[['person frustrated talking to camera','young adult awkward conversation'],['person nervous conversation','student frustrated phone'],['person embarrassed reaction','young person confused'],['young person happy discovery','person smiling phone']],rules:{noProductBeforeLast:true,noMascotBeforeReveal:true,ugcFirst:true,ctaLast:true,maxSeconds:15}}));}
function rankConcepts(pool){return pool.map(c=>({...c,gate:qualityGate(c)})).filter(c=>c.gate.pass).sort((a,b)=>b.gate.score-a.gate.score).slice(0,50)}
function showConcepts(concepts){const box=document.createElement('section');box.className='variants';box.innerHTML=`<h2>🏆 ${concepts.length} concepts filtrés</h2><p>Le moteur élimine tout concept qui révèle le produit trop tôt. Les meilleurs sont en haut.</p>`;concepts.slice(0,10).forEach((c,i)=>{const el=document.createElement('div');el.className=`variant ${i===0?'selected':''}`;el.innerHTML=`<b>#${i+1} · ${c.id} · ${c.gate.score}/100</b><div class="concept-hook">${c.hook}</div><div class="concept-lines">${c.lines.slice(1).map(x=>`<span>${x}</span>`).join('')}</div><button type="button" class="pick" data-id="${c.id}">Choisir ce concept</button>`;box.appendChild(el)});box.querySelectorAll('.pick').forEach(btn=>btn.addEventListener('click',()=>{selectedConcept=concepts.find(c=>c.id===btn.dataset.id)||concepts[0];box.querySelectorAll('.variant').forEach(x=>x.classList.remove('selected'));btn.closest('.variant').classList.add('selected');$('status').textContent=`Concept ${selectedConcept.id} sélectionné. Recherche des plans…`}));return box}
async function searchQueries(queries,locale,targetDuration){const key=JSON.stringify({queries,locale,targetDuration});if(clipCache.has(key))return clipCache.get(key);const r=await fetch('/api/pexels',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({queries,locale,target_duration:targetDuration,per_page:10})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Erreur Pexels');const vids=(data.videos||[]).filter(v=>Number(v.height)>=Number(v.width)).sort((a,b)=>(b.score||0)-(a.score||0));clipCache.set(key,vids);return vids}
function proxyUrl(url){return `/api/pexels-proxy?url=${encodeURIComponent(url)}`}
function makeCard(v,scene){const card=document.createElement('article');card.className='card';card.innerHTML=`<div class="scene">Scène ${scene}</div><video src="${v.url}" poster="${v.image}" muted playsinline loop preload="metadata"></video><div class="meta"><div class="score">${Number(v.score||0).toFixed(1)} · ${Number(v.duration||0).toFixed(1)}s</div><div class="query">${v.query}</div><div class="credit">${v.photographer} · Pexels</div></div>`;const vid=card.querySelector('video');card.addEventListener('mouseenter',()=>vid.play().catch(()=>{}));card.addEventListener('mouseleave',()=>{vid.pause();vid.currentTime=0});return card}
async function findClips(concept,seconds,showUI=true,variantIndex=0){const cfg=marketConfig[concept.market],all=[];for(let i=0;i<concept.searches.length;i++){if(showUI)$('status').textContent=`🎥 Plans ${i+1}/4 — recherche UGC/POV…`;const vids=await searchQueries(concept.searches[i],cfg.locale,Math.max(1,seconds/9));const candidates=vids.slice(0,8);if(showUI){const section=document.createElement('section');section.className='scene-block';section.innerHTML=`<h2>Scène ${i+1}</h2><p>${['Le hook / réaction','La frustration','Le moment gênant','La découverte'][i]}</p>`;const grid=document.createElement('div');grid.className='scene-grid';candidates.forEach(v=>grid.appendChild(makeCard(v,i+1)));section.appendChild(grid);$('results').appendChild(section)}if(candidates.length)all.push({...candidates[(variantIndex+i)%candidates.length],renderUrl:proxyUrl(candidates[(variantIndex+i)%candidates.length].url)})}return all}
async function renderConcept(concept,index,seconds){const videos=await findClips(concept,seconds,false,index);if(videos.length<4)throw new Error('moins de 4 plans verticaux utilisables');const r=await renderCreative({videos,lines:concept.lines,duration:seconds,onProgress:p=>$('status').textContent=`🤖 Créa ${index+1}/50 — rendu ${p}%`});const response=await fetch(r.url);const blob=await response.blob();const stored=await saveVideo({id:`${concept.market}-${index}`,index,conceptId:concept.id,filename:`sunami-${concept.market}-${String(index+1).padStart(2,'0')}.${r.filename.endsWith('.mp4')?'mp4':'webm'}`,type:blob.type,blob});return {stored,filename:r.filename,url:r.url};}
async function renderNow(){const status=$('status'),out=$('output'),duration=Number($('duration').value),btn=$('render');if(!selectedConcept||bestVideos.length<4){status.textContent='Il manque un concept ou 4 plans utilisables.';return}btn.disabled=true;status.textContent='🎬 Montage TikTok-first…';try{const r=await renderCreative({videos:bestVideos,lines:selectedConcept.lines,duration,onProgress:p=>status.textContent=`🎬 Montage TikTok-first… ${p}%`});out.innerHTML=`<section class="panel"><h2>🎬 Meilleure créa</h2><video controls playsinline src="${r.url}" style="width:min(360px,100%);border-radius:18px"></video><p><a class="download" download="${r.filename}" href="${r.url}">⬇ Télécharger ${r.filename}</a></p><small>Clips Pexels · rendu local gratuit · ${r.filename.endsWith('.mp4')?'MP4':'WebM'}</small></section>`;status.textContent='✅ Créa terminée.';out.scrollIntoView({behavior:'smooth',block:'start'});await refreshLibrary()}catch(e){status.textContent=`Rendu impossible : ${e.message}`}finally{btn.disabled=false}}
async function autopilot(){const market=$('market').value,seconds=Number($('duration').value),brief=$('brief').value.trim(),button=$('autopilot');button.disabled=true;$('generate').disabled=true;$('render').disabled=true;$('results').innerHTML='';$('output').innerHTML='';try{$('status').textContent='🧠 50 angles + règles TikTok…';const concepts=rankConcepts(conceptPool(market,brief));$('results').appendChild(showConcepts(concepts));for(let i=0;i<concepts.length;i++){try{const r=await renderConcept(concepts[i],i,seconds);$('status').textContent=`🤖 ${i+1}/50 terminée — ${r.stored?'sauvegardée':'rendu disponible'}`;await refreshLibrary()}catch(e){console.warn('concept rejected',i,e);$('status').textContent=`🤖 ${i+1}/50 rejetée — passage à la suivante`}}$('status').textContent='🏁 Autopilot terminé. Les vidéos acceptées sont dans la bibliothèque.'}catch(e){$('status').textContent=`Autopilot arrêté : ${e.message}`}finally{button.disabled=false;$('generate').disabled=false;await refreshLibrary()}}
async function run(){const market=$('market').value,seconds=Number($('duration').value),brief=$('brief').value.trim(),status=$('status'),results=$('results'),generate=$('generate'),renderBtn=$('render');results.innerHTML='';$('output').innerHTML='';bestVideos=[];selectedConcept=null;generate.disabled=true;renderBtn.disabled=true;try{status.textContent='🧠 Génération de 50 angles…';const concepts=rankConcepts(conceptPool(market,brief));selectedConcept=concepts[0];results.appendChild(showConcepts(concepts));bestVideos=await findClips(selectedConcept,seconds,true,0);renderBtn.disabled=bestVideos.length<4;if(bestVideos.length>=4)await renderNow();else status.textContent='Pexels n’a pas fourni 4 plans verticaux utilisables. Relance pour une autre sélection.'}catch(e){status.textContent=e.message}finally{generate.disabled=false}}
$('generate').addEventListener('click',run);$('render').addEventListener('click',renderNow);$('autopilot').addEventListener('click',autopilot);refreshLibrary();
if(new URLSearchParams(location.search).get('autopilot')==='50'){setTimeout(autopilot,700)}
