import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { useState } from 'react';
import { Alert, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { StatusBar } from 'expo-status-bar';
import Animated, { FadeInDown, FadeInRight } from 'react-native-reanimated';
import { AnimatedPressable } from '../components/AnimatedPressable';
import { MascotComponent } from '../components/MascotComponent';
import { RootStackParamList } from '../navigation/types';
import { colors, radius, shadow, spacing } from '../theme';

type Props = NativeStackScreenProps<RootStackParamList, 'Home'>;

export function HomeScreen({}: Props) {
  const [reaction, setReaction] = useState('Sunny est prêt pour toi.');
  return <SafeAreaView style={styles.safe} edges={['top']}>
    <StatusBar style="dark" />
    <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
      <View style={styles.header}><View><Text style={styles.logo}>sunami<Text style={styles.dot}>.</Text></Text><Text style={styles.headerMeta}>TON HISTOIRE DU JOUR</Text></View><AnimatedPressable style={styles.avatarButton} onPress={() => Alert.alert('Ton profil', 'La page profil arrive bientôt.')}><Text style={styles.avatarEmoji}>🙂</Text></AnimatedPressable></View>
      <Animated.View entering={FadeInDown.duration(450)} style={styles.greetingBlock}><Text style={styles.greeting}>Bonjour, aventurier <Text style={styles.wave}>✦</Text></Text><Text style={styles.subtitle}>Ton histoire t’attend.</Text></Animated.View>
      <Animated.View entering={FadeInDown.delay(80).duration(450)} style={styles.streakCard}><View><Text style={styles.streakLabel}>SÉRIE EN COURS</Text><Text style={styles.streakNumber}>7 <Text style={styles.streakUnit}>jours</Text></Text><Text style={styles.streakHint}>Encore 10 XP pour battre ton record.</Text></View><View style={styles.fireCircle}><Text style={styles.fire}>🔥</Text></View></Animated.View>
      <Animated.View entering={FadeInRight.delay(160).duration(500)} style={styles.mascotSection}><MascotComponent onReact={() => setReaction('Sunny adore ta motivation ! ✦')} /><Text style={styles.reaction}>{reaction}</Text></Animated.View>
      <Animated.View entering={FadeInDown.delay(220).duration(450)} style={styles.storyCard}><View style={styles.storyTop}><View><Text style={styles.storyEyebrow}>ÉPISODE 01 · LE DÉPART</Text><Text style={styles.storyTitle}>Le train pour Marseille</Text></View><Text style={styles.storyIcon}>↗</Text></View><Text style={styles.storyBody}>Quelqu’un t’attend sur le quai. Ta prochaine réponse changera la suite de l’histoire.</Text><View style={styles.progressMeta}><Text style={styles.progressText}>PROGRESSION</Text><Text style={styles.progressText}>2 / 5</Text></View><View style={styles.progressTrack}><View style={styles.progressFill} /></View><AnimatedPressable style={styles.continueButton} onPress={() => Alert.alert('Épisode 01', 'Le lecteur d’histoire sera bientôt connecté à ton compte.')}><Text style={styles.continueText}>Continuer l’histoire</Text><Text style={styles.continueArrow}>→</Text></AnimatedPressable></Animated.View>
      <View style={styles.sectionHeader}><Text style={styles.sectionTitle}>Ton rythme</Text><Text style={styles.seeAll}>Voir tout</Text></View><View style={styles.statsRow}><StatCard icon="⭐" value="120" label="XP cette semaine" /><StatCard icon="◒" value="18" label="mots découverts" /></View>
    </ScrollView>
  </SafeAreaView>;
}

function StatCard({ icon, value, label }: { icon: string; value: string; label: string }) { return <Animated.View entering={FadeInDown.delay(300).duration(400)} style={styles.statCard}><Text style={styles.statIcon}>{icon}</Text><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></Animated.View>; }

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.paper }, content: { paddingHorizontal: spacing.lg, paddingBottom: spacing.xxl },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingTop: spacing.sm }, logo: { color: colors.ink, fontSize: 24, fontWeight: '800', letterSpacing: -1 }, dot: { color: colors.limeDark }, headerMeta: { color: colors.muted, fontSize: 9, fontWeight: '700', letterSpacing: 1.2, marginTop: 3 },
  avatarButton: { width: 44, height: 44, borderRadius: 22, backgroundColor: colors.white, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.line }, avatarEmoji: { fontSize: 20 }, greetingBlock: { marginTop: spacing.xl }, greeting: { color: colors.ink, fontSize: 30, fontWeight: '800', letterSpacing: -1 }, wave: { color: colors.limeDark }, subtitle: { color: colors.muted, fontSize: 15, marginTop: 3 },
  streakCard: { marginTop: spacing.lg, borderRadius: radius.md, backgroundColor: colors.inkSoft, padding: spacing.lg, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', ...shadow }, streakLabel: { color: colors.teal, fontSize: 10, fontWeight: '800', letterSpacing: 1.1 }, streakNumber: { color: colors.white, fontSize: 30, fontWeight: '800', letterSpacing: -1, marginTop: 5 }, streakUnit: { color: colors.white, fontSize: 14, fontWeight: '500' }, streakHint: { color: '#B6C8BF', fontSize: 11, marginTop: 2 }, fireCircle: { width: 60, height: 60, borderRadius: 30, backgroundColor: colors.lime, alignItems: 'center', justifyContent: 'center' }, fire: { fontSize: 30 },
  mascotSection: { alignItems: 'center', marginTop: spacing.xl }, reaction: { color: colors.muted, fontSize: 12, marginTop: spacing.sm }, storyCard: { backgroundColor: colors.white, borderRadius: radius.lg, padding: spacing.lg, marginTop: spacing.xl, borderWidth: 1, borderColor: colors.line, ...shadow }, storyTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, storyEyebrow: { color: colors.limeDark, fontSize: 10, fontWeight: '800', letterSpacing: 1 }, storyTitle: { color: colors.ink, fontSize: 23, fontWeight: '800', letterSpacing: -0.7, marginTop: 6 }, storyIcon: { color: colors.limeDark, backgroundColor: colors.tealSoft, width: 38, height: 38, borderRadius: 19, textAlign: 'center', textAlignVertical: 'center', fontSize: 20 }, storyBody: { color: colors.muted, fontSize: 13, lineHeight: 19, marginTop: spacing.md }, progressMeta: { flexDirection: 'row', justifyContent: 'space-between', marginTop: spacing.lg }, progressText: { color: colors.muted, fontSize: 10, fontWeight: '800', letterSpacing: 0.7 }, progressTrack: { height: 7, backgroundColor: colors.line, borderRadius: 99, overflow: 'hidden', marginTop: 8 }, progressFill: { width: '40%', height: '100%', backgroundColor: colors.limeDark, borderRadius: 99 },
  continueButton: { marginTop: spacing.lg, backgroundColor: colors.lime, borderRadius: radius.pill, height: 50, paddingHorizontal: spacing.lg, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, continueText: { color: colors.ink, fontSize: 14, fontWeight: '800' }, continueArrow: { color: colors.ink, fontSize: 21, fontWeight: '700' }, sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: spacing.xl }, sectionTitle: { color: colors.ink, fontSize: 18, fontWeight: '800' }, seeAll: { color: colors.limeDark, fontSize: 12, fontWeight: '700' }, statsRow: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.sm }, statCard: { flex: 1, backgroundColor: colors.white, borderRadius: radius.md, padding: spacing.md, borderWidth: 1, borderColor: colors.line }, statIcon: { fontSize: 18 }, statValue: { color: colors.ink, fontSize: 23, fontWeight: '800', marginTop: 6 }, statLabel: { color: colors.muted, fontSize: 11, marginTop: 1 },
});
